find_path(SIMPLEAI_INCLUDE_DIR SimpleAI.h
  HINTS
    ENV SIMPLEAIDIR
  PATH_SUFFIXES include/simpleai include
)

find_library(SIMPLEAI_LIBRARY
  NAMES simpleai
  HINTS
    ENV SIMPLEAIDIR
  PATH_SUFFIXES lib
)

set(SIMPLEAI_LIBRARIES ${SIMPLEAI_LIBRARY})
set(SIMPLEAI_INCLUDE_DIRS ${SIMPLEAI_INCLUDE_DIR})
include(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(simpleai REQUIRED_VARS SIMPLEAI_LIBRARIES SIMPLEAI_INCLUDE_DIRS)
mark_as_advanced(SIMPLEAI_LIBRARY SIMPLEAI_INCLUDE_DIR)
